// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkealvbucatrvrdpghyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrZWFsdmJ1Y2F0cnZyZHBnaHl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyOTcwNjgsImV4cCI6MjA1MTg3MzA2OH0.vLjHdv6EbsbXkLL1csQUGpJhLtS1Dv0vQXgtEHTG0ys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);